## Spam classifier using BOW,TF-idf,word2vec,avgword2vec

In [2]:
import pandas as pd

In [219]:
data = pd.read_csv("C:\\Users\\neeli\\Downloads\\SMSSpamCollection (1).txt", sep='\t',
                           names=["label", "message"])

In [220]:
data

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [386]:
data.shape

(5572, 2)

## Creating bag of words

In [387]:
import re

In [388]:
import nltk

In [389]:
from nltk.corpus import stopwords

In [390]:
from nltk.stem.porter import PorterStemmer

In [391]:
ps = PorterStemmer()

In [392]:
stopwords=stopwords.words('english')

In [393]:
corpus = []

In [394]:
for i in range(len(data)):
    review = re.sub('[^a-zA-Z]', ' ', data['message'][i])
    review = review.lower()
    review = review.split( )
    
    review = [ps.stem(word) for word in review if not word in stopwords]
    review = ' '.join(review)
    corpus.append(review)

In [395]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

## Creating the Bag of Words model

In [396]:
from sklearn.feature_extraction.text import CountVectorizer

In [397]:
cv = CountVectorizer(max_features=2500)

In [398]:
X = cv.fit_transform(corpus).toarray()

In [399]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [416]:
X.shape

(5572, 2500)

In [418]:
y=pd.get_dummies(data['label'])
y=y.iloc[:,1].values

In [423]:
y

array([False, False,  True, ..., False, False, False])

In [367]:
from sklearn.model_selection import train_test_split

In [420]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)


In [369]:
from sklearn.naive_bayes import MultinomialNB

In [370]:
spam_detection = MultinomialNB()

In [422]:
spam_detect_model= spam_detection.fit(X_train,y_train)

In [30]:
y_predict=spam_detect_model.predict(X_test)

In [31]:
y_predict

array([False,  True, False, ..., False,  True, False])

In [32]:
from sklearn.metrics import accuracy_score,classification_report

In [33]:
accuracy= accuracy_score(y_predict,y_test)

In [34]:
accuracy

0.9856502242152466

In [35]:
print(classification_report(y_predict,y_test))

              precision    recall  f1-score   support

       False       0.99      0.99      0.99       953
        True       0.96      0.94      0.95       162

    accuracy                           0.99      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



## Creating the TFIDF model

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [464]:
tv = TfidfVectorizer()

In [465]:
X = tv.fit_transform(corpus)

In [466]:
X.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [467]:
from sklearn.naive_bayes import MultinomialNB

In [468]:
spam_detect_model = MultinomialNB().fit(X_train, y_train)

In [469]:
y_pred=spam_detect_model.predict(X_test)

In [43]:
score=accuracy_score(y_test,y_pred)
print(score)

0.9856502242152466


In [44]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

       False       0.99      0.99      0.99       953
        True       0.96      0.94      0.95       162

    accuracy                           0.99      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



### Word2vec Implementation

In [45]:
pip install timmins

In [50]:
pip install gensim

Note: you may need to restart the kernel to use updated packages.


In [52]:
import gensim.downloader as api

In [53]:
wv = api.load('word2vec-google-news-300')

[===-----------------------------------------------] 8.0% 132.7/1662.8MB downloaded

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



[===========---------------------------------------] 23.7% 393.8/1662.8MB downloaded

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



[=============================================-----] 90.3% 1501.1/1662.8MB downloaded

In [54]:
from nltk.stem import WordNetLemmatizer

In [55]:
lemmatizer = WordNetLemmatizer()

In [70]:
corpus=[]

In [232]:
corpus = []
for i in range(0, len(data['message'])):
    review = re.sub('[^a-zA-Z]', ' ', data['message'][i])
    review = review.lower()
    review = review.split()
    
    review = [lemmatizer.lemmatize(word) for word in review if not word in stopwords]
    review = ' '.join(review)
    corpus.append(review)

In [233]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

In [234]:
from nltk import sent_tokenize

In [235]:
from gensim.utils import simple_preprocess

In [236]:
corpus[0]

'go jurong point crazy available bugis n great world la e buffet cine got amore wat'

In [237]:
words=[]

In [238]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [239]:
words

[['go',
  'jurong',
  'point',
  'crazy',
  'available',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'wkly',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply'],
 ['dun', 'say', 'early', 'hor', 'already', 'say'],
 ['nah', 'think', 'go', 'usf', 'life', 'around', 'though'],
 ['freemsg',
  'hey',
  'darling',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'caller',
  'press',
  'copy',
  'friend',
  'callertune'],
 ['winner',
  'valued',
  'network',
  'customer',
  'selected',
  'receivea',
 

In [240]:
import gensim

In [241]:
model = gensim.models.Word2Vec(words,window=5,min_count=2)

In [242]:
model.wv.index_to_key

['call',
 'get',
 'ur',
 'gt',
 'lt',
 'go',
 'ok',
 'day',
 'free',
 'know',
 'come',
 'like',
 'time',
 'good',
 'got',
 'love',
 'text',
 'want',
 'send',
 'need',
 'one',
 'txt',
 'today',
 'going',
 'stop',
 'home',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'think',
 'tell',
 'week',
 'hi',
 'phone',
 'new',
 'later',
 'please',
 'pls',
 'co',
 'msg',
 'min',
 'make',
 'night',
 'dear',
 'message',
 'well',
 'say',
 'thing',
 'much',
 'oh',
 'hope',
 'claim',
 'great',
 'hey',
 'give',
 'number',
 'happy',
 'wat',
 'friend',
 'work',
 'way',
 'yes',
 'www',
 'prize',
 'let',
 'right',
 'tomorrow',
 'already',
 'tone',
 'ask',
 'win',
 'said',
 'life',
 'cash',
 'amp',
 'yeah',
 'im',
 'really',
 'meet',
 'babe',
 'find',
 'miss',
 'morning',
 'thanks',
 'last',
 'uk',
 'service',
 'year',
 'anything',
 'care',
 'would',
 'com',
 'also',
 'lol',
 'nokia',
 'feel',
 'every',
 'keep',
 'sure',
 'pick',
 'urgent',
 'sent',
 'contact',


In [243]:
dir(wv)

['__class__',
 '__contains__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_adapt_by_suffix',
 '_load_specials',
 '_log_evaluate_word_analogies',
 '_save_specials',
 '_smart_save',
 '_upconvert_old_d2vkv',
 '_upconvert_old_vocab',
 'add_lifecycle_event',
 'add_vector',
 'add_vectors',
 'allocate_vecattrs',
 'closer_than',
 'cosine_similarities',
 'distance',
 'distances',
 'doesnt_match',
 'evaluate_word_analogies',
 'evaluate_word_pairs',
 'expandos',
 'fill_norms',
 'get_index',
 'get_mean_vector',
 'get_normed_vectors',
 'get_vecattr',
 'get_vector',
 'has_index_for',
 'index2entity',
 'index2word',
 'index_to_key'

In [244]:
model.wv.similar_by_word('call')

[('mobile', 0.9996312260627747),
 ('please', 0.9995558261871338),
 ('free', 0.9995471835136414),
 ('cash', 0.9995341897010803),
 ('line', 0.9995317459106445),
 ('claim', 0.9995247721672058),
 ('service', 0.9995182156562805),
 ('number', 0.9994977712631226),
 ('text', 0.9994804263114929),
 ('reply', 0.9994688630104065)]

In [245]:
model.wv.index_to_key

['call',
 'get',
 'ur',
 'gt',
 'lt',
 'go',
 'ok',
 'day',
 'free',
 'know',
 'come',
 'like',
 'time',
 'good',
 'got',
 'love',
 'text',
 'want',
 'send',
 'need',
 'one',
 'txt',
 'today',
 'going',
 'stop',
 'home',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'think',
 'tell',
 'week',
 'hi',
 'phone',
 'new',
 'later',
 'please',
 'pls',
 'co',
 'msg',
 'min',
 'make',
 'night',
 'dear',
 'message',
 'well',
 'say',
 'thing',
 'much',
 'oh',
 'hope',
 'claim',
 'great',
 'hey',
 'give',
 'number',
 'happy',
 'wat',
 'friend',
 'work',
 'way',
 'yes',
 'www',
 'prize',
 'let',
 'right',
 'tomorrow',
 'already',
 'tone',
 'ask',
 'win',
 'said',
 'life',
 'cash',
 'amp',
 'yeah',
 'im',
 'really',
 'meet',
 'babe',
 'find',
 'miss',
 'morning',
 'thanks',
 'last',
 'uk',
 'service',
 'year',
 'anything',
 'care',
 'would',
 'com',
 'also',
 'lol',
 'nokia',
 'feel',
 'every',
 'keep',
 'sure',
 'pick',
 'urgent',
 'sent',
 'contact',


In [246]:
model.wv['free'] - model.wv['win']

array([-0.01767555, -0.00262648,  0.00510693,  0.01237661,  0.02014763,
        0.01815569,  0.00152001, -0.01920414, -0.00324991,  0.00161609,
        0.0035578 , -0.00410318,  0.01475763, -0.01353136,  0.00465757,
       -0.01525319, -0.0141301 , -0.00024831, -0.01330601,  0.01057982,
        0.01531464,  0.00116536,  0.01370111, -0.01029372,  0.02044795,
       -0.00241397, -0.00172463, -0.01338238, -0.00971362, -0.03441741,
        0.00432885, -0.01350553,  0.01977909,  0.01339838,  0.00634268,
        0.00667697, -0.00384693,  0.00338891, -0.00144112, -0.01363093,
       -0.01809902,  0.00239909, -0.00865705, -0.00665615, -0.00632435,
       -0.00931108,  0.00619331,  0.00722619,  0.00028315, -0.00097585,
        0.0057146 ,  0.00736392,  0.00297873, -0.00812465,  0.0038802 ,
       -0.01075026,  0.0136109 ,  0.00723377,  0.01451755, -0.00653547,
       -0.01381408, -0.00885254,  0.01811579, -0.0123419 , -0.02323073,
        0.00465438, -0.02180536,  0.01913503, -0.01219726, -0.01

In [247]:
type(model.wv.index_to_key)

list

In [248]:
model.corpus_count

5564

In [249]:
model.epochs

5

In [250]:
import numpy as np

In [472]:
def avg_word2vec(doc):
    # remove out-of-vocabulary words
    
    #sent = [word for word in doc if word in model.wv.index_to_key
    
    #print(sent)

     return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)

In [252]:
pip install tqdm

Note: you may need to restart the kernel to use updated packages.


In [254]:
words[73]

['performed']

In [255]:
len(words)

5564

In [256]:
x=[]
for i in range(len(words)):
    print('sentences',[i])
    x.append(avg_word2vec(words[i]))

sentences [0]
sentences [1]
sentences [2]
sentences [3]
sentences [4]
sentences [5]
sentences [6]
sentences [7]
sentences [8]
sentences [9]
sentences [10]
sentences [11]
sentences [12]
sentences [13]
sentences [14]
sentences [15]
sentences [16]
sentences [17]
sentences [18]
sentences [19]
sentences [20]
sentences [21]
sentences [22]
sentences [23]
sentences [24]
sentences [25]
sentences [26]
sentences [27]
sentences [28]
sentences [29]
sentences [30]
sentences [31]
sentences [32]
sentences [33]
sentences [34]
sentences [35]
sentences [36]
sentences [37]
sentences [38]
sentences [39]
sentences [40]
sentences [41]
sentences [42]
sentences [43]
sentences [44]
sentences [45]
sentences [46]
sentences [47]
sentences [48]
sentences [49]
sentences [50]
sentences [51]
sentences [52]
sentences [53]
sentences [54]
sentences [55]
sentences [56]
sentences [57]
sentences [58]
sentences [59]
sentences [60]
sentences [61]
sentences [62]
sentences [63]
sentences [64]
sentences [65]
sentences [66]
sente

C:\Users\neeli\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\neeli\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


sentences [1289]
sentences [1290]
sentences [1291]
sentences [1292]
sentences [1293]
sentences [1294]
sentences [1295]
sentences [1296]
sentences [1297]
sentences [1298]
sentences [1299]
sentences [1300]
sentences [1301]
sentences [1302]
sentences [1303]
sentences [1304]
sentences [1305]
sentences [1306]
sentences [1307]
sentences [1308]
sentences [1309]
sentences [1310]
sentences [1311]
sentences [1312]
sentences [1313]
sentences [1314]
sentences [1315]
sentences [1316]
sentences [1317]
sentences [1318]
sentences [1319]
sentences [1320]
sentences [1321]
sentences [1322]
sentences [1323]
sentences [1324]
sentences [1325]
sentences [1326]
sentences [1327]
sentences [1328]
sentences [1329]
sentences [1330]
sentences [1331]
sentences [1332]
sentences [1333]
sentences [1334]
sentences [1335]
sentences [1336]
sentences [1337]
sentences [1338]
sentences [1339]
sentences [1340]
sentences [1341]
sentences [1342]
sentences [1343]
sentences [1344]
sentences [1345]
sentences [1346]
sentences [134

In [257]:
x

[array([-0.1029757 ,  0.2962035 ,  0.14412884,  0.03341115,  0.03484927,
        -0.32417074,  0.08413447,  0.5251859 , -0.16160218, -0.1560474 ,
        -0.15399584, -0.34600142, -0.00469038,  0.09838501,  0.07626835,
        -0.28727904,  0.02040157, -0.34412262, -0.01759157, -0.44567433,
         0.07127911,  0.15667768,  0.10078102, -0.12674   , -0.11242631,
         0.0274948 , -0.21501571, -0.14869423, -0.22352089,  0.04906451,
         0.28868082,  0.05582571,  0.14846781, -0.23570652, -0.11953837,
         0.26179263,  0.03475288, -0.1936662 , -0.17438865, -0.36688724,
         0.06510939, -0.22948706, -0.09807608,  0.04948874,  0.24697018,
        -0.13482545, -0.17531998,  0.0346722 ,  0.14782736,  0.23877484,
         0.17260505, -0.2899602 , -0.05223447, -0.02368668, -0.13285826,
         0.20726544,  0.17762005, -0.03800136, -0.26754028,  0.06916297,
         0.10619676,  0.12236104, -0.13357064,  0.00122544, -0.2657429 ,
         0.15896116,  0.08645228,  0.19568019, -0.2

In [346]:
words[0]

['go',
 'jurong',
 'point',
 'crazy',
 'available',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'got',
 'amore',
 'wat']

In [359]:
x[0]   # 100 dimension vector for first sentence

array([-0.1029757 ,  0.2962035 ,  0.14412884,  0.03341115,  0.03484927,
       -0.32417074,  0.08413447,  0.5251859 , -0.16160218, -0.1560474 ,
       -0.15399584, -0.34600142, -0.00469038,  0.09838501,  0.07626835,
       -0.28727904,  0.02040157, -0.34412262, -0.01759157, -0.44567433,
        0.07127911,  0.15667768,  0.10078102, -0.12674   , -0.11242631,
        0.0274948 , -0.21501571, -0.14869423, -0.22352089,  0.04906451,
        0.28868082,  0.05582571,  0.14846781, -0.23570652, -0.11953837,
        0.26179263,  0.03475288, -0.1936662 , -0.17438865, -0.36688724,
        0.06510939, -0.22948706, -0.09807608,  0.04948874,  0.24697018,
       -0.13482545, -0.17531998,  0.0346722 ,  0.14782736,  0.23877484,
        0.17260505, -0.2899602 , -0.05223447, -0.02368668, -0.13285826,
        0.20726544,  0.17762005, -0.03800136, -0.26754028,  0.06916297,
        0.10619676,  0.12236104, -0.13357064,  0.00122544, -0.2657429 ,
        0.15896116,  0.08645228,  0.19568019, -0.28144044,  0.32

In [361]:
X_new=np.array(X)

In [362]:
X_new

array([array([-0.1029757 ,  0.2962035 ,  0.14412884,  0.03341115,  0.03484927,
              -0.32417074,  0.08413447,  0.5251859 , -0.16160218, -0.1560474 ,
              -0.15399584, -0.34600142, -0.00469038,  0.09838501,  0.07626835,
              -0.28727904,  0.02040157, -0.34412262, -0.01759157, -0.44567433,
               0.07127911,  0.15667768,  0.10078102, -0.12674   , -0.11242631,
               0.0274948 , -0.21501571, -0.14869423, -0.22352089,  0.04906451,
               0.28868082,  0.05582571,  0.14846781, -0.23570652, -0.11953837,
               0.26179263,  0.03475288, -0.1936662 , -0.17438865, -0.36688724,
               0.06510939, -0.22948706, -0.09807608,  0.04948874,  0.24697018,
              -0.13482545, -0.17531998,  0.0346722 ,  0.14782736,  0.23877484,
               0.17260505, -0.2899602 , -0.05223447, -0.02368668, -0.13285826,
               0.20726544,  0.17762005, -0.03800136, -0.26754028,  0.06916297,
               0.10619676,  0.12236104, -0.13357064,

In [363]:
y

array([0, 0, 1, ..., 0, 0, 0])

In [364]:
from sklearn.model_selection import train_test_split

In [424]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [454]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB( ).fit(X_train, y_train)

In [455]:
y_predict=spam_detect_model.predict(X_train)

In [456]:
y_predict

array([False, False, False, ...,  True, False, False])

In [457]:
from sklearn.metrics import accuracy_score,classification_report

In [458]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

       False       0.99      0.99      0.99       953
        True       0.96      0.94      0.95       162

    accuracy                           0.99      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [459]:
score=accuracy_score(y_test,y_pred)
print(score)

0.9856502242152466
